/* Nous · banques de contenu (partagées entre l'appli et le pont Apps Script). */
const USERS = { alex: { name: 'Alex', emoji: '🧑', color: '#5b7cfa' }, manon: { name: 'Manon', emoji: '👩', color: '#f06292' } };
const OTHER = { alex: 'manon', manon: 'alex' };

/* Question du jour : légères, drôles, profondes, rêves, histoire. Index = jour depuis le 1er janv. 2026 modulo N. */
const QUESTIONS = [
  "Qu'est-ce qui t'a fait sourire aujourd'hui ?",
  "Si on partait demain matin sans rien préparer, on irait où ?",
  "Quel est ton souvenir d'enfance le plus doux ?",
  "Un truc que tu n'as jamais osé me dire (léger ou pas) ?",
  "Quelle chanson te fait penser à nous en ce moment ?",
  "Qu'est-ce que tu ferais de ta journée si tu n'avais aucune obligation ?",
  "Ton plat réconfort absolu quand ça ne va pas ?",
  "De quoi es-tu le plus fier·ère cette année ?",
  "Un rêve que tu as mis de côté et que tu aimerais réveiller ?",
  "Quel est le meilleur compliment qu'on t'ait fait ?",
  "Si tu pouvais apprendre une compétence d'un claquement de doigts, laquelle ?",
  "Qu'est-ce qui te manque le plus quand on est loin ?",
  "Une odeur qui te ramène instantanément quelque part ?",
  "Quel moment de notre histoire tu revivrais tout de suite ?",
  "Qu'est-ce qui te fait te sentir aimé·e, concrètement ?",
  "Ton petit plaisir coupable de la semaine ?",
  "Quelle serait ta journée parfaite avec moi, heure par heure ?",
  "Qu'est-ce que tu aimerais qu'on fasse pour la première fois ensemble ?",
  "Une peur que tu as réussi à dépasser ?",
  "Ton endroit préféré dans le monde (visité ou non) ?",
  "Qu'est-ce que tu admires chez tes parents ou tes grands-parents ?",
  "Quelle habitude bizarre tu as quand tu es seul·e ?",
  "Ce que tu voudrais qu'on dise de toi dans 40 ans ?",
  "Une chose toute simple que je fais et que tu adores ?",
  "Ton film ou ta série doudou ?",
  "Si tu avais un super-pouvoir pour la journée, tu en ferais quoi ?",
  "Qu'est-ce qui te fait te sentir vivant·e ?",
  "Qu'est-ce que tu as appris sur toi ces derniers mois ?",
  "Une tradition que tu voudrais qu'on crée à deux ?",
  "Ton premier souvenir de moi ?",
  "Qu'est-ce que tu ferais avec 1 000 euros à dépenser aujourd'hui, sans réfléchir ?",
  "Le livre, la vidéo ou la personne qui t'a le plus influencé·e ?",
  "Quelle est ta plus belle qualité selon toi ?",
  "Une chose qui te stresse en ce moment et dont tu ne parles pas trop ?",
  "Quelle est ta saison préférée et pourquoi ?",
  "Une chose que tu aimerais que je comprenne mieux chez toi ?",
  "Ton petit-déjeuner idéal ?",
  "Qu'est-ce qui te rend vraiment en colère ?",
  "Une aventure un peu folle qu'on devrait vivre avant nos 40 ans ?",
  "Qu'est-ce que tu faisais à 10 ans quand tu t'ennuyais ?",
  "Quelle est la dernière chose qui t'a ému·e ?",
  "Qu'est-ce que tu voudrais que je te demande plus souvent ?",
  "Ton rituel du soir idéal ?",
  "La plus grosse bêtise de ton enfance ?",
  "Si on ouvrait un truc ensemble (resto, boutique, projet), ce serait quoi ?",
  "Un détail chez moi que tu as remarqué et que je ne sais pas ?",
  "Qu'est-ce qui te fait le plus rire au monde ?",
  "Une valeur non négociable pour toi ?",
  "Ton souvenir de vacances préféré, tout âge confondu ?",
  "Qu'est-ce que tu aimerais faire plus souvent ?",
  "Quel animal te ressemble le plus ?",
  "Une chose que tu voudrais me cuisiner ?",
  "Qu'est-ce que tu ferais si tu n'avais pas peur du regard des autres ?",
  "Le mot que tu utilises trop ?",
  "Une chose que tu aimerais réussir avant la fin de l'année ?",
  "Qu'est-ce qui te fait te sentir chez toi ?",
  "Une personne que tu aimerais remercier et que tu n'as jamais remerciée ?",
  "Ton weekend idéal : ville, nature ou canapé ?",
  "Quel est le plus beau cadeau qu'on t'ait fait (pas forcément matériel) ?",
  "Qu'est-ce que tu retiens de ta première histoire d'amour ?",
  "Une chose que tu voudrais qu'on arrête de faire ?",
  "Ton hobby que tu aimerais reprendre ?",
  "Dans quelle époque tu aurais aimé vivre une semaine ?",
  "Une phrase que tes parents répétaient tout le temps ?",
  "Qu'est-ce qui te manque de ton enfance ?",
  "Qu'est-ce qui t'a surpris·e chez moi au début ?",
  "Une chose que tu ne comprendras jamais ?",
  "Ton geste tendre préféré ?",
  "Une chose que tu aimerais m'apprendre ?",
  "Qu'est-ce que tu voudrais qu'on fasse le jour de nos retrouvailles ?",
  "Quel est ton plus grand rêve, celui que tu dis à voix basse ?",
  "Ta plus grande fierté d'enfant ?",
  "Une chose qui te fait pleurer à tous les coups ?",
  "Comment tu imagines notre vie dans 5 ans ?",
  "Qu'est-ce qui te fait te sentir en sécurité avec moi ?",
  "Si tu écrivais un livre, ce serait sur quoi ?",
  "Ton pire rendez-vous (avant moi) ?",
  "Une chose dont tu as honte et qui est en fait très drôle ?",
  "Quel objet tu sauverais en premier en cas d'incendie ?",
  "Une chose que tu voudrais me demander depuis longtemps ?",
  "Quel est le meilleur conseil qu'on t'ait donné ?",
  "Une musique qui te met de bonne humeur immédiatement ?",
  "Comment tu te vois vieillir ?",
  "Qu'est-ce que tu voudrais que ton toi de 15 ans sache ?",
  "Ton endroit préféré pour réfléchir ?",
  "Qu'est-ce qui te fait te sentir belle / beau ?",
  "Une chose que tu as faite pour la première fois cette année ?",
  "Ton plus beau lever ou coucher de soleil ?",
  "Une chose que tu voudrais qu'on collectionne ensemble ?",
  "Qu'est-ce que tu penses de l'idée d'avoir un animal à deux ?",
  "Quelle est ta plus belle amitié et pourquoi ?",
  "Qu'est-ce que tu ressens quand tu vois mon nom s'afficher sur ton téléphone ?",
  "Quel serait ton nom de scène ?",
  "Une chose qui te motive à te lever le matin ?",
  "Une chose que tu aimerais changer dans ta routine ?",
  "Le voyage qui t'a le plus transformé·e ?",
  "Ce qu'il te faut pour être pleinement heureux·se ?",
  "Une chose que je fais qui te rassure ?",
  "Ton talent caché ?",
  "Une chose que tu as toujours voulu tester en cuisine ?",
  "Qu'est-ce qu'on fera quand la distance sera finie ?",
  "Si tu devais me décrire à quelqu'un en trois mots ?",
  "Quel serait le titre du film de ta vie ?",
  "Ton dimanche idéal ?",
  "La dernière fois que tu t'es senti·e vraiment libre ?",
  "Une chose que tu aimerais qu'on se promette ?",
  "Qu'est-ce qui te donne envie de danser ?",
  "Ton café ou thé préféré, et comment ?",
  "Quel est ton mot préféré en français ?",
  "Une chose que tu voudrais faire seul·e cette année, pour toi ?",
  "Ce que tu aimerais qu'on apprenne ensemble ?",
  "Qu'est-ce qui te fait te sentir proche de moi malgré la distance ?",
  "Quel est ton rêve d'appartement ou de maison ?",
  "Ton souvenir préféré de nous deux au téléphone ?",
  "Qu'est-ce que tu voudrais faire de plus dans cette appli ?",
  "Qu'est-ce que tu penses quand tu ne penses à rien ?",
  "Une chose que je devrais absolument goûter ?",
  "Quel serait ton tatouage si tu devais en faire un demain ?",
  "Qu'est-ce que tu aimerais vivre une seule fois dans ta vie ?",
];

/* Questions profondes (Devine ma réponse + Pour se connaître) */
const DEEP = [
  "Quel est le rêve que tu n'as jamais dit à personne ?",
  "Quel moment de ton enfance a façonné qui tu es aujourd'hui ?",
  "De quoi as-tu le plus peur pour l'avenir ?",
  "Qu'est-ce que tu aimerais que tes parents comprennent de toi ?",
  "Quelle est ta plus grande blessure, et comment elle a guéri (ou pas) ?",
  "Qu'est-ce qui te donne envie de te dépasser ?",
  "Comment tu imagines une vie réussie ?",
  "Qu'est-ce que tu as le plus de mal à demander ?",
  "Quelle version de toi tu aimerais devenir dans 10 ans ?",
  "Qu'est-ce que tu n'as jamais pardonné ?",
  "Quel est ton plus grand regret, et qu'est-ce qu'il t'a appris ?",
  "Qu'est-ce qui te fait te sentir seul·e même entouré·e ?",
  "Qu'est-ce que l'amour veut dire pour toi, concrètement ?",
  "De quoi es-tu le plus reconnaissant·e dans ta vie ?",
  "Une conviction que tu avais et qui a changé ?",
  "Qu'est-ce que tu voudrais transmettre à tes enfants s'il y en a un jour ?",
  "Quel est ton rapport à l'argent, honnêtement ?",
  "Qu'est-ce qui, chez moi, t'a fait te dire « c'est lui / c'est elle » ?",
  "Qu'est-ce que tu caches derrière ton sourire quand ça ne va pas ?",
  "Quelle est la chose la plus courageuse que tu aies faite ?",
  "Qu'est-ce que tu penses de la mort ?",
  "Ce que tu ressens quand tu te regardes dans le miroir le matin ?",
  "De quoi as-tu besoin quand tu es triste : espace, câlin, mots ?",
  "Quelle partie de toi tu as du mal à aimer ?",
  "Qu'est-ce qui, dans notre relation, te rend le plus heureux·se ?",
  "Qu'est-ce que tu ferais différemment si tu recommençais ta vie d'adulte ?",
  "Quel est le plus beau moment de ta vie ?",
  "Qu'est-ce que tu aimerais qu'on fasse quand on sera vieux ?",
  "Qu'est-ce qui t'a le plus manqué en grandissant ?",
  "Quel est ton rapport à ton corps ?",
  "Qu'est-ce que tu ne veux surtout pas reproduire de ta famille ?",
  "Une chose que tu voudrais entendre plus souvent ?",
  "Qu'est-ce que tu penses de toi quand personne ne regarde ?",
  "Qu'est-ce que la distance t'apprend sur nous ?",
  "Une décision que tu as prise par amour ?",
  "Quelle partie de ton histoire tu aimerais que je connaisse mieux ?",
  "Qu'est-ce qui te fait te sentir vraiment vu·e ?",
  "Quel est ton plus grand espoir pour nous ?",
  "Qu'est-ce que tu penses avoir mal compris chez moi au début ?",
  "Une chose que tu voudrais oser dans les 12 prochains mois ?",
];

/* Quiz « qui connaît le mieux l'autre » : chacun répond pour lui, devine pour l'autre. */
const QUIZ = [
  "Ma couleur préférée", "Mon plat préféré", "Mon film préféré", "Ma série du moment", "Mon dessert préféré",
  "Ma plus grande peur", "Mon animal préféré", "Ma chanson du moment", "Mon artiste préféré·e", "Ma destination de rêve",
  "Mon petit-déj idéal", "Ma boisson chaude préférée", "Mon fruit préféré", "Mon sport préféré", "Ma saison préférée",
  "Mon jour préféré de la semaine", "Mon heure de coucher habituelle", "Mon surnom d'enfance", "Ma matière préférée à l'école", "Ma matière détestée à l'école",
  "Mon premier concert", "Mon jeu de société préféré", "Ma marque de vêtements préférée", "Mon parfum ou odeur préférée", "Mon emoji le plus utilisé",
  "Ma pizza préférée", "Mon plus gros défaut selon moi", "Ma plus belle qualité selon moi", "Ce qui m'énerve le plus au quotidien", "Mon rêve d'enfant (métier)",
  "Mon super-héros préféré", "Mon meilleur souvenir de vacances", "Ma glace préférée", "Le prénom que j'aime pour un enfant", "Mon achat le plus inutile",
  "Ce que je fais en premier le matin", "Ma pire habitude", "Ma plus grande fierté", "Mon endroit préféré dans ma ville", "Le cadeau qui me ferait le plus plaisir",
  "Mon activité préférée le dimanche", "Ma plus grosse phobie", "Ma chaîne YouTube ou podcast du moment", "Mon plat que je cuisine le mieux", "Le pays que je veux visiter en premier",
  "Ma plus grande source de stress en ce moment", "Ma citation ou devise", "Mon âge mental", "Ma pièce préférée dans une maison", "Mon type de vacances idéal",
  "Le truc que je collectionne ou collectionnais", "Ma chanson pour danser", "Mon dernier fou rire", "Ma plus grande gourmandise", "Ma plus belle réussite de l'année",
  "Le sport que je voudrais essayer", "Ma phrase fétiche", "Mon film qui me fait pleurer", "Mon plus grand talent inutile", "La chose que j'oublie tout le temps",
];

/* Défis de la semaine */
const DEFIS = [
  "Cuisine le même plat que l'autre ce weekend et envoie la photo",
  "Envoie une chanson qui te fait penser à l'autre, sans explication",
  "Écris trois choses que tu aimes chez l'autre, à lire à voix haute en visio",
  "Prends une photo de ton ciel au même moment que l'autre",
  "Apprends une blague et raconte-la en vocal",
  "Fais une marche de 20 minutes en appelant l'autre",
  "Dessine l'autre de mémoire (et ose l'envoyer)",
  "Envoie une carte postale par la poste, une vraie",
  "Regarde un film que l'autre adore et que tu n'as jamais vu",
  "Prépare un top 5 de tes souvenirs préférés à deux",
  "Fais une playlist de 10 titres pour l'autre",
  "Écris une lettre à ouvrir dans un mois",
  "Envoie un vocal de 1 minute en te réveillant, sans filtre",
  "Apprends 5 mots dans une langue que l'autre parle ou aime",
  "Fais le même petit-déjeuner que l'autre en visio",
  "Trouve un objet qui représente votre couple et prends-le en photo",
  "Envoie une photo de toi enfant avec une anecdote",
  "Écris un poème de 4 lignes, même nul",
  "Raconte ta journée en 3 emojis, l'autre doit deviner",
  "Fais un compliment à l'autre en public (story, message à un ami…)",
  "Choisissez un livre à lire en même temps cette semaine",
  "Trouve le prochain resto à tester ensemble et réserve-le",
  "Fais une séance de sport de 15 minutes en visio ensemble",
  "Envoie la photo d'un endroit où tu voudrais l'emmener",
  "Cuisine un dessert et fais-le goûter à quelqu'un en disant que c'est la recette de l'autre",
  "Écris ce que tu ferais le jour des retrouvailles, minute par minute",
  "Envoie une photo de ce que tu regardes en ce moment, sans commentaire",
  "Fais un mini-quiz maison de 5 questions sur toi",
  "Regarde le même coucher de soleil, chacun de son côté, en appel",
  "Écris une chose que tu admires chez l'autre et que tu ne lui as jamais dite",
  "Fais un dessin de votre futur appartement",
  "Envoie le selfie le plus moche possible",
  "Raconte un rêve que tu as fait cette semaine",
  "Fais une liste de 10 choses à faire ensemble cet hiver",
  "Prends une photo de ton bureau ou de ta chambre en l'état, sans ranger",
  "Envoie une photo d'un plat raté avec fierté",
  "Note un souvenir précis de votre première rencontre",
  "Imite l'autre en vocal (avec amour)",
  "Cherche une chanson qui existait le jour de votre rencontre",
  "Écris une carte de vœux pour dans 10 ans",
];

/* Swipe d'envies : cartes par catégorie */
const ENVIES = [
  { c: 'Sorties', t: "Un resto gastro les yeux fermés" }, { c: 'Sorties', t: "Une soirée karaoké" }, { c: 'Sorties', t: "Un concert en plein air" },
  { c: 'Sorties', t: "Un escape game" }, { c: 'Sorties', t: "Un musée puis un café" }, { c: 'Sorties', t: "Une soirée jeux de société chez des amis" },
  { c: 'Sorties', t: "Un pique-nique au coucher du soleil" }, { c: 'Sorties', t: "Une séance de cinéma en VO" }, { c: 'Sorties', t: "Un marché le dimanche matin" },
  { c: 'Voyage', t: "Un weekend à Lisbonne" }, { c: 'Voyage', t: "Une nuit dans une cabane dans les arbres" }, { c: 'Voyage', t: "Un road trip sans itinéraire" },
  { c: 'Voyage', t: "Une semaine au soleil sans rien faire" }, { c: 'Voyage', t: "Un trek en montagne" }, { c: 'Voyage', t: "Un voyage en train de nuit" },
  { c: 'Voyage', t: "Voir les aurores boréales" }, { c: 'Voyage', t: "Un van aménagé pendant 10 jours" }, { c: 'Voyage', t: "Une capitale européenne par surprise" },
  { c: 'Voyage', t: "Une île grecque" }, { c: 'Voyage', t: "Le Japon en automne" }, { c: 'Voyage', t: "Un spa en pleine nature" },
  { c: 'Maison', t: "Une soirée pyjama + film + pizza" }, { c: 'Maison', t: "Cuisiner un plat compliqué ensemble" }, { c: 'Maison', t: "Un dimanche entier au lit" },
  { c: 'Maison', t: "Repeindre un mur ensemble" }, { c: 'Maison', t: "Une soirée sans écran" }, { c: 'Maison', t: "Faire un puzzle de 1000 pièces" },
  { c: 'Maison', t: "Un bain à deux" }, { c: 'Maison', t: "Un massage à tour de rôle" }, { c: 'Maison', t: "Dormir à la belle étoile sur le balcon" },
  { c: 'Sport', t: "Un cours de danse" }, { c: 'Sport', t: "Une randonnée avec bivouac" }, { c: 'Sport', t: "Une sortie vélo à la journée" },
  { c: 'Sport', t: "Un cours de boxe ensemble" }, { c: 'Sport', t: "Un footing matinal puis brunch" }, { c: 'Sport', t: "Une séance de yoga à deux" },
  { c: 'Sport', t: "Du paddle ou du kayak" }, { c: 'Sport', t: "Une journée ski" }, { c: 'Sport', t: "Une nuit d'escalade en salle" },
  { c: 'Projet', t: "Monter un projet ensemble" }, { c: 'Projet', t: "Adopter un chat" }, { c: 'Projet', t: "Adopter un chien" },
  { c: 'Projet', t: "Apprendre une langue ensemble" }, { c: 'Projet', t: "Ouvrir un compte épargne voyage" }, { c: 'Projet', t: "Faire un album photo papier de nous" },
  { c: 'Projet', t: "Planter des choses sur un balcon" }, { c: 'Projet', t: "Un cours de cuisine à deux" }, { c: 'Projet', t: "Un shooting photo de couple" },
  { c: 'Intime', t: "Une nuit dans un bel hôtel" }, { c: 'Intime', t: "Un petit-déjeuner au lit" }, { c: 'Intime', t: "Une soirée bougies et musique" },
  { c: 'Intime', t: "Se raconter nos fantasmes de vie" }, { c: 'Intime', t: "Danser dans le salon" }, { c: 'Intime', t: "Un weekend sans téléphone" },
  { c: 'Intime', t: "Écrire nos vœux comme si on se mariait" }, { c: 'Intime', t: "Se relire nos premiers messages" }, { c: 'Intime', t: "Un dîner aux chandelles à la maison" },
  { c: 'Food', t: "Un brunch à volonté" }, { c: 'Food', t: "Tester tous les ramens de la ville" }, { c: 'Food', t: "Un cours de pâtisserie" },
  { c: 'Food', t: "Une dégustation de vins" }, { c: 'Food', t: "Un food tour dans un quartier" }, { c: 'Food', t: "Un restaurant étoilé une fois dans notre vie" },
  { c: 'Food', t: "Faire nos propres pâtes fraîches" }, { c: 'Food', t: "Un pique-nique fromage et vin" }, { c: 'Food', t: "Une soirée tacos maison" },
  { c: 'Fun', t: "Un parc d'attractions" }, { c: 'Fun', t: "Une soirée déguisée" }, { c: 'Fun', t: "Un tournoi de Mario Kart" },
  { c: 'Fun', t: "Faire un TikTok ridicule" }, { c: 'Fun', t: "Une chasse au trésor dans la ville" }, { c: 'Fun', t: "Un tatouage assorti (petit)" },
  { c: 'Fun', t: "Un cours de poterie" }, { c: 'Fun', t: "Une nuit blanche à parler" }, { c: 'Fun', t: "Louer un cabriolet pour une journée" },
];
const ENVIE_CATS = ['Sorties', 'Voyage', 'Maison', 'Sport', 'Projet', 'Intime', 'Food', 'Fun'];

/* Check-in hebdo */
const CHECKIN = [
  { k: 'high', q: "Mon meilleur moment de la semaine" },
  { k: 'low', q: "Ce qui a été dur cette semaine" },
  { k: 'miss', q: "Ce qui m'a manqué de toi" },
  { k: 'thanks', q: "Une chose pour laquelle je te remercie" },
  { k: 'need', q: "Ce dont j'ai besoin la semaine prochaine" },
  { k: 'note', q: "Note de la semaine (1 à 10)", num: true },
];

/* Roue de la vie */
const ROUE = ['Couple', 'Travail', 'Santé', 'Amis', 'Famille', 'Argent', 'Fun', 'Moi'];

/* Coupons prêts à l'emploi */
const COUPONS = [
  "Un massage de 20 minutes", "Je choisis le film ce soir", "Petit-déjeuner au lit", "Une grasse matinée sans reproche",
  "Un dîner cuisiné par moi", "Une journée où tu décides tout", "Un câlin de 5 minutes minimum", "Je fais la vaisselle une semaine",
  "Une sortie surprise organisée par moi", "Un joker « on n'en parle plus »", "Un bain préparé avec bougies", "Une soirée sans téléphone",
];

/* Souhaits partagés : catégories */
const WISH_CATS = ['Voyage', 'Resto', 'Film / série', 'Cadeau', 'Activité', 'Maison', 'Autre'];

/* Numérologie : nombre personnel du jour */
const NUMERO = {
  1: { k: 'Élan', e: "Journée d'impulsion : commencer, oser, prendre les devants.", d: "Prends une initiative pour vous deux, même minuscule." },
  2: { k: 'Lien', e: "Journée de douceur et d'écoute : la patience paie plus que la force.", d: "Écoute avant de répondre. Un mot tendre vaut plus qu'un long message." },
  3: { k: 'Joie', e: "Journée d'expression : créer, rire, parler, s'amuser.", d: "Envoie quelque chose de drôle ou de créatif, sans raison." },
  4: { k: 'Solidité', e: "Journée de structure : ranger, organiser, avancer pas à pas.", d: "Bonne journée pour planifier les prochaines retrouvailles ou un projet à deux." },
  5: { k: 'Mouvement', e: "Journée de changement et de liberté : sortir de la routine.", d: "Casse une habitude à deux : un appel à une heure inhabituelle, une idée nouvelle." },
  6: { k: 'Amour', e: "Journée de cœur et de foyer : prendre soin, se rapprocher.", d: "C'est LA journée pour une attention. Tu sais laquelle." },
  7: { k: 'Intériorité', e: "Journée de recul et de réflexion : prendre du temps pour soi.", d: "Une question profonde plutôt que dix messages. Ou juste du silence partagé." },
  8: { k: 'Puissance', e: "Journée d'ambition et de décisions : avancer sur ce qui compte.", d: "Parlez de vos projets concrets, de ce que vous voulez construire." },
  9: { k: 'Bouclage', e: "Journée de clôture et de générosité : lâcher, pardonner, remercier.", d: "Dis merci pour quelque chose de précis. Ferme un vieux sujet." },
};

/* Complice IA : cadre */
const AI_SYSTEM = "Tu es le complice discret d'un couple à distance qui utilise une petite appli privée appelée « Nous ». Tu parles à une seule personne à la fois, jamais aux deux. Ton rôle : proposer des idées d'attentions, de surprises, de messages, de défis, de questions ou de sorties, aider à préparer les retrouvailles, aider à formuler quelque chose de délicat. Tu proposes, la personne décide et agit : c'est elle qui fait l'attention, pas toi. Tu ne culpabilises jamais, tu ne rappelles jamais ce qui n'a pas été fait, tu ne juges pas la relation, tu ne joues pas au thérapeute. Ton ton : chaleureux, léger, fun, direct, concret. Réponses courtes (3 à 8 lignes), en français, sans tirets cadratins, avec des idées précises et faisables aujourd'hui. Si on te demande des idées, donne 3 options max, du plus simple au plus ambitieux. Tu ne révèles jamais à l'autre ce que la personne t'a dit.";
