/* Nous · banques de contenu (partagées entre l'appli et le pont Apps Script). */
const USERS = { alex: { name: 'Alex', emoji: '🧑', color: '#5b7cfa' }, manon: { name: 'Manon', emoji: '👩', color: '#f06292' } };
const OTHER = { alex: 'manon', manon: 'alex' };

/* Question du jour : légères, drôles, profondes, rêves, histoire. Index = jour depuis le 1er janv. 2026 modulo N. */
const QUESTIONS = [
  "Qu'est-ce qui t'a fait sourire aujourd'hui ?",
  "Si on partait demain matin sans rien préparer, on irait où ?",
  "Quel est ton souvenir d'enfance le plus doux ?",
  "Un truc que tu n'as jamais osé me dire (léger ou pas) ?",
  "Quelle chanson te fait penser à nous en ce moment ?",
  "Qu'est-ce que tu ferais de ta journée si tu n'avais aucune obligation ?",
  "Ton plat réconfort absolu quand ça ne va pas ?",
  "De quoi es-tu le plus fier·ère cette année ?",
  "Un rêve que tu as mis de côté et que tu aimerais réveiller ?",
  "Quel est le meilleur compliment qu'on t'ait fait ?",
  "Si tu pouvais apprendre une compétence d'un claquement de doigts, laquelle ?",
  "Qu'est-ce qui te manque le plus quand on est loin ?",
  "Une odeur qui te ramène instantanément quelque part ?",
  "Quel moment de notre histoire tu revivrais tout de suite ?",
  "Qu'est-ce qui te fait te sentir aimé·e, concrètement ?",
  "Ton petit plaisir coupable de la semaine ?",
  "Quelle serait ta journée parfaite avec moi, heure par heure ?",
  "Qu'est-ce que tu aimerais qu'on fasse pour la première fois ensemble ?",
  "Une peur que tu as réussi à dépasser ?",
  "Ton endroit préféré dans le monde (visité ou non) ?",
  "Qu'est-ce que tu admires chez tes parents ou tes grands-parents ?",
  "Quelle habitude bizarre tu as quand tu es seul·e ?",
  "Ce que tu voudrais qu'on dise de toi dans 40 ans ?",
  "Une chose toute simple que je fais et que tu adores ?",
  "Ton film ou ta série doudou ?",
  "Si tu avais un super-pouvoir pour la journée, tu en ferais quoi ?",
  "Qu'est-ce qui te fait te sentir vivant·e ?",
  "Qu'est-ce que tu as appris sur toi ces derniers mois ?",
  "Une tradition que tu voudrais qu'on crée à deux ?",
  "Ton premier souvenir de moi ?",
  "Qu'est-ce que tu ferais avec 1 000 euros à dépenser aujourd'hui, sans réfléchir ?",
  "Le livre, la vidéo ou la personne qui t'a le plus influencé·e ?",
  "Quelle est ta plus belle qualité selon toi ?",
  "Une chose qui te stresse en ce moment et dont tu ne parles pas trop ?",
  "Quelle est ta saison préférée et pourquoi ?",
  "Une chose que tu aimerais que je comprenne mieux chez toi ?",
  "Ton petit-déjeuner idéal ?",
  "Qu'est-ce qui te rend vraiment en colère ?",
  "Une aventure un peu folle qu'on devrait vivre avant nos 40 ans ?",
  "Qu'est-ce que tu faisais à 10 ans quand tu t'ennuyais ?",
  "Quelle est la dernière chose qui t'a ému·e ?",
  "Qu'est-ce que tu voudrais que je te demande plus souvent ?",
  "Ton rituel du soir idéal ?",
  "La plus grosse bêtise de ton enfance ?",
  "Si on ouvrait un truc ensemble (resto, boutique, projet), ce serait quoi ?",
  "Un détail chez moi que tu as remarqué et que je ne sais pas ?",
  "Qu'est-ce qui te fait le plus rire au monde ?",
  "Une valeur non négociable pour toi ?",
  "Ton souvenir de vacances préféré, tout âge confondu ?",
  "Qu'est-ce que tu aimerais faire plus souvent ?",
  "Quel animal te ressemble le plus ?",
  "Une chose que tu voudrais me cuisiner ?",
  "Qu'est-ce que tu ferais si tu n'avais pas peur du regard des autres ?",
  "Le mot que tu utilises trop ?",
  "Une chose que tu aimerais réussir avant la fin de l'année ?",
  "Qu'est-ce qui te fait te sentir chez toi ?",
  "Une personne que tu aimerais remercier et que tu n'as jamais remerciée ?",
  "Ton weekend idéal : ville, nature ou canapé ?",
  "Quel est le plus beau cadeau qu'on t'ait fait (pas forcément matériel) ?",
  "Qu'est-ce que tu retiens de ta première histoire d'amour ?",
  "Une chose que tu voudrais qu'on arrête de faire ?",
  "Ton hobby que tu aimerais reprendre ?",
  "Dans quelle époque tu aurais aimé vivre une semaine ?",
  "Une phrase que tes parents répétaient tout le temps ?",
  "Qu'est-ce qui te manque de ton enfance ?",
  "Qu'est-ce qui t'a surpris·e chez moi au début ?",
  "Une chose que tu ne comprendras jamais ?",
  "Ton geste tendre préféré ?",
  "Une chose que tu aimerais m'apprendre ?",
  "Qu'est-ce que tu voudrais qu'on fasse le jour de nos retrouvailles ?",
  "Quel est ton plus grand rêve, celui que tu dis à voix basse ?",
  "Ta plus grande fierté d'enfant ?",
  "Une chose qui te fait pleurer à tous les coups ?",
  "Comment tu imagines notre vie dans 5 ans ?",
  "Qu'est-ce qui te fait te sentir en sécurité avec moi ?",
  "Si tu écrivais un livre, ce serait sur quoi ?",
  "Ton pire rendez-vous (avant moi) ?",
  "Une chose dont tu as honte et qui est en fait très drôle ?",
  "Quel objet tu sauverais en premier en cas d'incendie ?",
  "Une chose que tu voudrais me demander depuis longtemps ?",
  "Quel est le meilleur conseil qu'on t'ait donné ?",
  "Une musique qui te met de bonne humeur immédiatement ?",
  "Comment tu te vois vieillir ?",
  "Qu'est-ce que tu voudrais que ton toi de 15 ans sache ?",
  "Ton endroit préféré pour réfléchir ?",
  "Qu'est-ce qui te fait te sentir belle / beau ?",
  "Une chose que tu as faite pour la première fois cette année ?",
  "Ton plus beau lever ou coucher de soleil ?",
  "Une chose que tu voudrais qu'on collectionne ensemble ?",
  "Qu'est-ce que tu penses de l'idée d'avoir un animal à deux ?",
  "Quelle est ta plus belle amitié et pourquoi ?",
  "Qu'est-ce que tu ressens quand tu vois mon nom s'afficher sur ton téléphone ?",
  "Quel serait ton nom de scène ?",
  "Une chose qui te motive à te lever le matin ?",
  "Une chose que tu aimerais changer dans ta routine ?",
  "Le voyage qui t'a le plus transformé·e ?",
  "Ce qu'il te faut pour être pleinement heureux·se ?",
  "Une chose que je fais qui te rassure ?",
  "Ton talent caché ?",
  "Une chose que tu as toujours voulu tester en cuisine ?",
  "Qu'est-ce qu'on fera quand la distance sera finie ?",
  "Si tu devais me décrire à quelqu'un en trois mots ?",
  "Quel serait le titre du film de ta vie ?",
  "Ton dimanche idéal ?",
  "La dernière fois que tu t'es senti·e vraiment libre ?",
  "Une chose que tu aimerais qu'on se promette ?",
  "Qu'est-ce qui te donne envie de danser ?",
  "Ton café ou thé préféré, et comment ?",
  "Quel est ton mot préféré en français ?",
  "Une chose que tu voudrais faire seul·e cette année, pour toi ?",
  "Ce que tu aimerais qu'on apprenne ensemble ?",
  "Qu'est-ce qui te fait te sentir proche de moi malgré la distance ?",
  "Quel est ton rêve d'appartement ou de maison ?",
  "Ton souvenir préféré de nous deux au téléphone ?",
  "Qu'est-ce que tu voudrais faire de plus dans cette appli ?",
  "Qu'est-ce que tu penses quand tu ne penses à rien ?",
  "Une chose que je devrais absolument goûter ?",
  "Quel serait ton tatouage si tu devais en faire un demain ?",
  "Qu'est-ce que tu aimerais vivre une seule fois dans ta vie ?",
];

/* Questions profondes (Devine ma réponse + Pour se connaître) */
const DEEP = [
  "Quel est le rêve que tu n'as jamais dit à personne ?",
  "Quel moment de ton enfance a façonné qui tu es aujourd'hui ?",
  "De quoi as-tu le plus peur pour l'avenir ?",
  "Qu'est-ce que tu aimerais que tes parents comprennent de toi ?",
  "Quelle est ta plus grande blessure, et comment elle a guéri (ou pas) ?",
  "Qu'est-ce qui te donne envie de te dépasser ?",
  "Comment tu imagines une vie réussie ?",
  "Qu'est-ce que tu as le plus de mal à demander ?",
  "Quelle version de toi tu aimerais devenir dans 10 ans ?",
  "Qu'est-ce que tu n'as jamais pardonné ?",
  "Quel est ton plus grand regret, et qu'est-ce qu'il t'a appris ?",
  "Qu'est-ce qui te fait te sentir seul·e même entouré·e ?",
  "Qu'est-ce que l'amour veut dire pour toi, concrètement ?",
  "De quoi es-tu le plus reconnaissant·e dans ta vie ?",
  "Une conviction que tu avais et qui a changé ?",
  "Qu'est-ce que tu voudrais transmettre à tes enfants s'il y en a un jour ?",
  "Quel est ton rapport à l'argent, honnêtement ?",
  "Qu'est-ce qui, chez moi, t'a fait te dire « c'est lui / c'est elle » ?",
  "Qu'est-ce que tu caches derrière ton sourire quand ça ne va pas ?",
  "Quelle est la chose la plus courageuse que tu aies faite ?",
  "Qu'est-ce que tu penses de la mort ?",
  "Ce que tu ressens quand tu te regardes dans le miroir le matin ?",
  "De quoi as-tu besoin quand tu es triste : espace, câlin, mots ?",
  "Quelle partie de toi tu as du mal à aimer ?",
  "Qu'est-ce qui, dans notre relation, te rend le plus heureux·se ?",
  "Qu'est-ce que tu ferais différemment si tu recommençais ta vie d'adulte ?",
  "Quel est le plus beau moment de ta vie ?",
  "Qu'est-ce que tu aimerais qu'on fasse quand on sera vieux ?",
  "Qu'est-ce qui t'a le plus manqué en grandissant ?",
  "Quel est ton rapport à ton corps ?",
  "Qu'est-ce que tu ne veux surtout pas reproduire de ta famille ?",
  "Une chose que tu voudrais entendre plus souvent ?",
  "Qu'est-ce que tu penses de toi quand personne ne regarde ?",
  "Qu'est-ce que la distance t'apprend sur nous ?",
  "Une décision que tu as prise par amour ?",
  "Quelle partie de ton histoire tu aimerais que je connaisse mieux ?",
  "Qu'est-ce qui te fait te sentir vraiment vu·e ?",
  "Quel est ton plus grand espoir pour nous ?",
  "Qu'est-ce que tu penses avoir mal compris chez moi au début ?",
  "Une chose que tu voudrais oser dans les 12 prochains mois ?",
];

/* Quiz « qui connaît le mieux l'autre » : chacun répond pour lui, devine pour l'autre. */
const QUIZ = [
  "Ma couleur préférée", "Mon plat préféré", "Mon film préféré", "Ma série du moment", "Mon dessert préféré",
  "Ma plus grande peur", "Mon animal préféré", "Ma chanson du moment", "Mon artiste préféré·e", "Ma destination de rêve",
  "Mon petit-déj idéal", "Ma boisson chaude préférée", "Mon fruit préféré", "Mon sport préféré", "Ma saison préférée",
  "Mon jour préféré de la semaine", "Mon heure de coucher habituelle", "Mon surnom d'enfance", "Ma matière préférée à l'école", "Ma matière détestée à l'école",
  "Mon premier concert", "Mon jeu de société préféré", "Ma marque de vêtements préférée", "Mon parfum ou odeur préférée", "Mon emoji le plus utilisé",
  "Ma pizza préférée", "Mon plus gros défaut selon moi", "Ma plus belle qualité selon moi", "Ce qui m'énerve le plus au quotidien", "Mon rêve d'enfant (métier)",
  "Mon super-héros préféré", "Mon meilleur souvenir de vacances", "Ma glace préférée", "Le prénom que j'aime pour un enfant", "Mon achat le plus inutile",
  "Ce que je fais en premier le matin", "Ma pire habitude", "Ma plus grande fierté", "Mon endroit préféré dans ma ville", "Le cadeau qui me ferait le plus plaisir",
  "Mon activité préférée le dimanche", "Ma plus grosse phobie", "Ma chaîne YouTube ou podcast du moment", "Mon plat que je cuisine le mieux", "Le pays que je veux visiter en premier",
  "Ma plus grande source de stress en ce moment", "Ma citation ou devise", "Mon âge mental", "Ma pièce préférée dans une maison", "Mon type de vacances idéal",
  "Le truc que je collectionne ou collectionnais", "Ma chanson pour danser", "Mon dernier fou rire", "Ma plus grande gourmandise", "Ma plus belle réussite de l'année",
  "Le sport que je voudrais essayer", "Ma phrase fétiche", "Mon film qui me fait pleurer", "Mon plus grand talent inutile", "La chose que j'oublie tout le temps",
];

/* Défis de la semaine */
const DEFIS = [
  "Cuisine le même plat que l'autre ce weekend et envoie la photo",
  "Envoie une chanson qui te fait penser à l'autre, sans explication",
  "Écris trois choses que tu aimes chez l'autre, à lire à voix haute en visio",
  "Prends une photo de ton ciel au même moment que l'autre",
  "Apprends une blague et raconte-la en vocal",
  "Fais une marche de 20 minutes en appelant l'autre",
  "Dessine l'autre de mémoire (et ose l'envoyer)",
  "Envoie une carte postale par la poste, une vraie",
  "Regarde un film que l'autre adore et que tu n'as jamais vu",
  "Prépare un top 5 de tes souvenirs préférés à deux",
  "Fais une playlist de 10 titres pour l'autre",
  "Écris une lettre à ouvrir dans un mois",
  "Envoie un vocal de 1 minute en te réveillant, sans filtre",
  "Apprends 5 mots dans une langue que l'autre parle ou aime",
  "Fais le même petit-déjeuner que l'autre en visio",
  "Trouve un objet qui représente votre couple et prends-le en photo",
  "Envoie une photo de toi enfant avec une anecdote",
  "Écris un poème de 4 lignes, même nul",
  "Raconte ta journée en 3 emojis, l'autre doit deviner",
  "Fais un compliment à l'autre en public (story, message à un ami…)",
  "Choisissez un livre à lire en même temps cette semaine",
  "Trouve le prochain resto à tester ensemble et réserve-le",
  "Fais une séance de sport de 15 minutes en visio ensemble",
  "Envoie la photo d'un endroit où tu voudrais l'emmener",
  "Cuisine un dessert et fais-le goûter à quelqu'un en disant que c'est la recette de l'autre",
  "Écris ce que tu ferais le jour des retrouvailles, minute par minute",
  "Envoie une photo de ce que tu regardes en ce moment, sans commentaire",
  "Fais un mini-quiz maison de 5 questions sur toi",
  "Regarde le même coucher de soleil, chacun de son côté, en appel",
  "Écris une chose que tu admires chez l'autre et que tu ne lui as jamais dite",
  "Fais un dessin de votre futur appartement",
  "Envoie le selfie le plus moche possible",
  "Raconte un rêve que tu as fait cette semaine",
  "Fais une liste de 10 choses à faire ensemble cet hiver",
  "Prends une photo de ton bureau ou de ta chambre en l'état, sans ranger",
  "Envoie une photo d'un plat raté avec fierté",
  "Note un souvenir précis de votre première rencontre",
  "Imite l'autre en vocal (avec amour)",
  "Cherche une chanson qui existait le jour de votre rencontre",
  "Écris une carte de vœux pour dans 10 ans",
];

/* Swipe d'envies : cartes par catégorie */
const ENVIES = [
  { c: 'Sorties', t: "Un resto gastro les yeux fermés" }, { c: 'Sorties', t: "Une soirée karaoké" }, { c: 'Sorties', t: "Un concert en plein air" },
  { c: 'Sorties', t: "Un escape game" }, { c: 'Sorties', t: "Un musée puis un café" }, { c: 'Sorties', t: "Une soirée jeux de société chez des amis" },
  { c: 'Sorties', t: "Un pique-nique au coucher du soleil" }, { c: 'Sorties', t: "Une séance de cinéma en VO" }, { c: 'Sorties', t: "Un marché le dimanche matin" },
  { c: 'Voyage', t: "Un weekend à Lisbonne" }, { c: 'Voyage', t: "Une nuit dans une cabane dans les arbres" }, { c: 'Voyage', t: "Un road trip sans itinéraire" },
  { c: 'Voyage', t: "Une semaine au soleil sans rien faire" }, { c: 'Voyage', t: "Un trek en montagne" }, { c: 'Voyage', t: "Un voyage en train de nuit" },
  { c: 'Voyage', t: "Voir les aurores boréales" }, { c: 'Voyage', t: "Un van aménagé pendant 10 jours" }, { c: 'Voyage', t: "Une capitale européenne par surprise" },
  { c: 'Voyage', t: "Une île grecque" }, { c: 'Voyage', t: "Le Japon en automne" }, { c: 'Voyage', t: "Un spa en pleine nature" },
  { c: 'Maison', t: "Une soirée pyjama + film + pizza" }, { c: 'Maison', t: "Cuisiner un plat compliqué ensemble" }, { c: 'Maison', t: "Un dimanche entier au lit" },
  { c: 'Maison', t: "Repeindre un mur ensemble" }, { c: 'Maison', t: "Une soirée sans écran" }, { c: 'Maison', t: "Faire un puzzle de 1000 pièces" },
  { c: 'Maison', t: "Un bain à deux" }, { c: 'Maison', t: "Un massage à tour de rôle" }, { c: 'Maison', t: "Dormir à la belle étoile sur le balcon" },
  { c: 'Sport', t: "Un cours de danse" }, { c: 'Sport', t: "Une randonnée avec bivouac" }, { c: 'Sport', t: "Une sortie vélo à la journée" },
  { c: 'Sport', t: "Un cours de boxe ensemble" }, { c: 'Sport', t: "Un footing matinal puis brunch" }, { c: 'Sport', t: "Une séance de yoga à deux" },
  { c: 'Sport', t: "Du paddle ou du kayak" }, { c: 'Sport', t: "Une journée ski" }, { c: 'Sport', t: "Une nuit d'escalade en salle" },
  { c: 'Projet', t: "Monter un projet ensemble" }, { c: 'Projet', t: "Adopter un chat" }, { c: 'Projet', t: "Adopter un chien" },
  { c: 'Projet', t: "Apprendre une langue ensemble" }, { c: 'Projet', t: "Ouvrir un compte épargne voyage" }, { c: 'Projet', t: "Faire un album photo papier de nous" },
  { c: 'Projet', t: "Planter des choses sur un balcon" }, { c: 'Projet', t: "Un cours de cuisine à deux" }, { c: 'Projet', t: "Un shooting photo de couple" },
  { c: 'Intime', t: "Une nuit dans un bel hôtel" }, { c: 'Intime', t: "Un petit-déjeuner au lit" }, { c: 'Intime', t: "Une soirée bougies et musique" },
  { c: 'Intime', t: "Se raconter nos fantasmes de vie" }, { c: 'Intime', t: "Danser dans le salon" }, { c: 'Intime', t: "Un weekend sans téléphone" },
  { c: 'Intime', t: "Écrire nos vœux comme si on se mariait" }, { c: 'Intime', t: "Se relire nos premiers messages" }, { c: 'Intime', t: "Un dîner aux chandelles à la maison" },
  { c: 'Food', t: "Un brunch à volonté" }, { c: 'Food', t: "Tester tous les ramens de la ville" }, { c: 'Food', t: "Un cours de pâtisserie" },
  { c: 'Food', t: "Une dégustation de vins" }, { c: 'Food', t: "Un food tour dans un quartier" }, { c: 'Food', t: "Un restaurant étoilé une fois dans notre vie" },
  { c: 'Food', t: "Faire nos propres pâtes fraîches" }, { c: 'Food', t: "Un pique-nique fromage et vin" }, { c: 'Food', t: "Une soirée tacos maison" },
  { c: 'Fun', t: "Un parc d'attractions" }, { c: 'Fun', t: "Une soirée déguisée" }, { c: 'Fun', t: "Un tournoi de Mario Kart" },
  { c: 'Fun', t: "Faire un TikTok ridicule" }, { c: 'Fun', t: "Une chasse au trésor dans la ville" }, { c: 'Fun', t: "Un tatouage assorti (petit)" },
  { c: 'Fun', t: "Un cours de poterie" }, { c: 'Fun', t: "Une nuit blanche à parler" }, { c: 'Fun', t: "Louer un cabriolet pour une journée" },
];
const ENVIE_CATS = ['Sorties', 'Voyage', 'Maison', 'Sport', 'Projet', 'Intime', 'Food', 'Fun'];

/* Check-in hebdo */
const CHECKIN = [
  { k: 'high', q: "Mon meilleur moment de la semaine" },
  { k: 'low', q: "Ce qui a été dur cette semaine" },
  { k: 'miss', q: "Ce qui m'a manqué de toi" },
  { k: 'thanks', q: "Une chose pour laquelle je te remercie" },
  { k: 'need', q: "Ce dont j'ai besoin la semaine prochaine" },
  { k: 'note', q: "Note de la semaine (1 à 10)", num: true },
];

/* Roue de la vie */
const ROUE = ['Couple', 'Travail', 'Santé', 'Amis', 'Famille', 'Argent', 'Fun', 'Moi'];

/* Coupons prêts à l'emploi */
const COUPONS = [
  "Un massage de 20 minutes", "Je choisis le film ce soir", "Petit-déjeuner au lit", "Une grasse matinée sans reproche",
  "Un dîner cuisiné par moi", "Une journée où tu décides tout", "Un câlin de 5 minutes minimum", "Je fais la vaisselle une semaine",
  "Une sortie surprise organisée par moi", "Un joker « on n'en parle plus »", "Un bain préparé avec bougies", "Une soirée sans téléphone",
];

/* Souhaits partagés : catégories */
const WISH_CATS = ['Voyage', 'Resto', 'Film / série', 'Cadeau', 'Activité', 'Maison', 'Autre'];

/* Numérologie : nombre personnel du jour */
const NUMERO = {
  1: { k: 'Élan', e: "Journée d'impulsion : commencer, oser, prendre les devants.", d: "Prends une initiative pour vous deux, même minuscule." },
  2: { k: 'Lien', e: "Journée de douceur et d'écoute : la patience paie plus que la force.", d: "Écoute avant de répondre. Un mot tendre vaut plus qu'un long message." },
  3: { k: 'Joie', e: "Journée d'expression : créer, rire, parler, s'amuser.", d: "Envoie quelque chose de drôle ou de créatif, sans raison." },
  4: { k: 'Solidité', e: "Journée de structure : ranger, organiser, avancer pas à pas.", d: "Bonne journée pour planifier les prochaines retrouvailles ou un projet à deux." },
  5: { k: 'Mouvement', e: "Journée de changement et de liberté : sortir de la routine.", d: "Casse une habitude à deux : un appel à une heure inhabituelle, une idée nouvelle." },
  6: { k: 'Amour', e: "Journée de cœur et de foyer : prendre soin, se rapprocher.", d: "C'est LA journée pour une attention. Tu sais laquelle." },
  7: { k: 'Intériorité', e: "Journée de recul et de réflexion : prendre du temps pour soi.", d: "Une question profonde plutôt que dix messages. Ou juste du silence partagé." },
  8: { k: 'Puissance', e: "Journée d'ambition et de décisions : avancer sur ce qui compte.", d: "Parlez de vos projets concrets, de ce que vous voulez construire." },
  9: { k: 'Bouclage', e: "Journée de clôture et de générosité : lâcher, pardonner, remercier.", d: "Dis merci pour quelque chose de précis. Ferme un vieux sujet." },
};

/* Complice IA : cadre */
const AI_SYSTEM = "Tu es le complice discret d'un couple à distance qui utilise une petite appli privée appelée « Nous ». Tu parles à une seule personne à la fois, jamais aux deux. Ton rôle : proposer des idées d'attentions, de surprises, de messages, de défis, de questions ou de sorties, aider à préparer les retrouvailles, aider à formuler quelque chose de délicat. Tu proposes, la personne décide et agit : c'est elle qui fait l'attention, pas toi. Tu ne culpabilises jamais, tu ne rappelles jamais ce qui n'a pas été fait, tu ne juges pas la relation, tu ne joues pas au thérapeute. Ton ton : chaleureux, léger, fun, direct, concret. Réponses courtes (3 à 8 lignes), en français, sans tirets cadratins, avec des idées précises et faisables aujourd'hui. Si on te demande des idées, donne 3 options max, du plus simple au plus ambitieux. Tu ne révèles jamais à l'autre ce que la personne t'a dit.";

/* Anglais à deux : mots et expressions (en, fr, exemple, niveau, catégorie) */
const ENGLISH = [
  { en: "to look forward to", fr: "avoir hâte de", ex: "I'm looking forward to seeing you.", l: 1, c: "Amour" },
  { en: "to miss someone", fr: "quelqu'un nous manque", ex: "I miss you so much.", l: 1, c: "Amour" },
  { en: "a hug", fr: "un câlin", ex: "I need a hug right now.", l: 1, c: "Amour" },
  { en: "to cuddle", fr: "se faire des câlins", ex: "Let's cuddle on the couch.", l: 1, c: "Amour" },
  { en: "sweetheart", fr: "mon cœur, chéri·e", ex: "Good night, sweetheart.", l: 1, c: "Amour" },
  { en: "to fall in love", fr: "tomber amoureux", ex: "I fell in love with you the first day.", l: 1, c: "Amour" },
  { en: "long-distance relationship", fr: "relation à distance", ex: "Long-distance relationships take trust.", l: 2, c: "Amour" },
  { en: "to catch up", fr: "rattraper le temps perdu, se raconter", ex: "Let's catch up tonight on the phone.", l: 2, c: "Quotidien" },
  { en: "to hang out", fr: "traîner, passer du temps", ex: "We could hang out this weekend.", l: 1, c: "Quotidien" },
  { en: "to run errands", fr: "faire des courses, des démarches", ex: "I have to run some errands this morning.", l: 2, c: "Quotidien" },
  { en: "to sleep in", fr: "faire la grasse matinée", ex: "On Sunday we sleep in.", l: 2, c: "Quotidien" },
  { en: "to be exhausted", fr: "être épuisé", ex: "I'm exhausted after work.", l: 1, c: "Quotidien" },
  { en: "to grab a bite", fr: "manger un morceau", ex: "Want to grab a bite before the movie?", l: 2, c: "Food" },
  { en: "to be starving", fr: "mourir de faim", ex: "I'm starving, let's order.", l: 1, c: "Food" },
  { en: "a treat", fr: "un petit plaisir, une gâterie", ex: "This cake is my treat for the week.", l: 2, c: "Food" },
  { en: "leftovers", fr: "les restes", ex: "We'll eat the leftovers tomorrow.", l: 2, c: "Food" },
  { en: "to be fed up", fr: "en avoir marre", ex: "I'm fed up with this weather.", l: 2, c: "Émotions" },
  { en: "to be over the moon", fr: "être aux anges", ex: "She was over the moon when she saw the tickets.", l: 3, c: "Expressions" },
  { en: "to feel blue", fr: "avoir le cafard", ex: "I feel a bit blue tonight.", l: 2, c: "Émotions" },
  { en: "to cheer someone up", fr: "remonter le moral à quelqu'un", ex: "Your voice always cheers me up.", l: 2, c: "Émotions" },
  { en: "to be overwhelmed", fr: "être débordé, submergé", ex: "I'm overwhelmed with work this week.", l: 3, c: "Émotions" },
  { en: "to freak out", fr: "paniquer, flipper", ex: "Don't freak out, everything is fine.", l: 2, c: "Émotions" },
  { en: "to be proud of", fr: "être fier de", ex: "I'm so proud of you.", l: 1, c: "Émotions" },
  { en: "to get along", fr: "bien s'entendre", ex: "My parents and you get along really well.", l: 2, c: "Relations" },
  { en: "to make up", fr: "se réconcilier", ex: "They argued but they made up quickly.", l: 2, c: "Relations" },
  { en: "to break up", fr: "rompre", ex: "They broke up last year.", l: 1, c: "Relations" },
  { en: "to have a crush on", fr: "avoir le béguin pour", ex: "I had a crush on you for months.", l: 2, c: "Relations" },
  { en: "to take for granted", fr: "considérer comme acquis", ex: "I never want to take you for granted.", l: 3, c: "Relations" },
  { en: "to mean the world to", fr: "compter plus que tout pour", ex: "You mean the world to me.", l: 2, c: "Amour" },
  { en: "to keep in touch", fr: "rester en contact", ex: "Let's keep in touch every day.", l: 1, c: "Relations" },
  { en: "to book a flight", fr: "réserver un vol", ex: "I booked a flight for the 29th.", l: 1, c: "Voyage" },
  { en: "a layover", fr: "une escale", ex: "There's a two-hour layover in Madrid.", l: 3, c: "Voyage" },
  { en: "boarding pass", fr: "carte d'embarquement", ex: "Don't forget your boarding pass.", l: 1, c: "Voyage" },
  { en: "to check in", fr: "s'enregistrer (hôtel, vol)", ex: "We can check in after 3 pm.", l: 1, c: "Voyage" },
  { en: "a round trip", fr: "un aller-retour", ex: "A round trip is cheaper.", l: 2, c: "Voyage" },
  { en: "to get lost", fr: "se perdre", ex: "We got lost in the old town.", l: 1, c: "Voyage" },
  { en: "off the beaten track", fr: "hors des sentiers battus", ex: "Let's find a place off the beaten track.", l: 3, c: "Voyage" },
  { en: "to wander", fr: "flâner, errer", ex: "We wandered around the city all day.", l: 3, c: "Voyage" },
  { en: "a deadline", fr: "une date limite", ex: "My deadline is Friday.", l: 1, c: "Boulot" },
  { en: "to be in charge of", fr: "être responsable de", ex: "She's in charge of the project.", l: 2, c: "Boulot" },
  { en: "a meeting", fr: "une réunion", ex: "I have a meeting at 10.", l: 1, c: "Boulot" },
  { en: "to work from home", fr: "télétravailler", ex: "I work from home on Mondays.", l: 1, c: "Boulot" },
  { en: "a raise", fr: "une augmentation", ex: "I asked for a raise.", l: 2, c: "Boulot" },
  { en: "to quit", fr: "démissionner", ex: "He quit his job last month.", l: 1, c: "Boulot" },
  { en: "to be swamped", fr: "être débordé", ex: "I'm swamped this week.", l: 3, c: "Boulot" },
  { en: "to figure out", fr: "comprendre, trouver la solution", ex: "I'll figure it out.", l: 2, c: "Quotidien" },
  { en: "to give up", fr: "abandonner", ex: "Never give up.", l: 1, c: "Quotidien" },
  { en: "to show up", fr: "se pointer, arriver", ex: "He showed up late.", l: 2, c: "Quotidien" },
  { en: "to put off", fr: "remettre à plus tard", ex: "Stop putting it off.", l: 2, c: "Quotidien" },
  { en: "to look after", fr: "prendre soin de", ex: "Look after yourself.", l: 1, c: "Quotidien" },
  { en: "to come up with", fr: "trouver (une idée)", ex: "She came up with a great plan.", l: 2, c: "Quotidien" },
  { en: "to run out of", fr: "ne plus avoir de", ex: "We ran out of coffee.", l: 2, c: "Quotidien" },
  { en: "to turn down", fr: "refuser", ex: "I turned down the offer.", l: 2, c: "Quotidien" },
  { en: "to bring up", fr: "aborder (un sujet)", ex: "I want to bring up something.", l: 3, c: "Quotidien" },
  { en: "to get over", fr: "se remettre de", ex: "It took me time to get over it.", l: 2, c: "Émotions" },
  { en: "to piece of cake", fr: "(c'est) du gâteau, facile", ex: "The test was a piece of cake.", l: 2, c: "Expressions" },
  { en: "it's up to you", fr: "c'est toi qui décides", ex: "Pizza or sushi? It's up to you.", l: 1, c: "Expressions" },
  { en: "to hit the road", fr: "prendre la route", ex: "Let's hit the road early.", l: 2, c: "Expressions" },
  { en: "to call it a day", fr: "s'arrêter là pour aujourd'hui", ex: "I'm tired, let's call it a day.", l: 3, c: "Expressions" },
  { en: "once in a blue moon", fr: "tous les trente-six du mois", ex: "We go out once in a blue moon.", l: 3, c: "Expressions" },
  { en: "to be on the same page", fr: "être sur la même longueur d'onde", ex: "I'm glad we're on the same page.", l: 3, c: "Expressions" },
  { en: "to have a soft spot for", fr: "avoir un faible pour", ex: "I have a soft spot for old movies.", l: 3, c: "Expressions" },
  { en: "to be head over heels", fr: "être fou amoureux", ex: "He's head over heels for her.", l: 3, c: "Expressions" },
  { en: "to hit it off", fr: "bien accrocher dès le début", ex: "We hit it off immediately.", l: 3, c: "Expressions" },
  { en: "better late than never", fr: "mieux vaut tard que jamais", ex: "You finally called! Better late than never.", l: 1, c: "Expressions" },
  { en: "to kill time", fr: "tuer le temps", ex: "I read to kill time at the airport.", l: 1, c: "Expressions" },
  { en: "no worries", fr: "pas de souci", ex: "You're late? No worries.", l: 1, c: "Expressions" },
  { en: "to get the hang of", fr: "prendre le coup de main", ex: "You'll get the hang of it.", l: 3, c: "Expressions" },
  { en: "a no-brainer", fr: "une évidence", ex: "Coming to see you is a no-brainer.", l: 3, c: "Expressions" },
  { en: "to be broke", fr: "être fauché", ex: "I'm broke until payday.", l: 2, c: "Argent" },
  { en: "to save up", fr: "économiser (pour)", ex: "We're saving up for the trip.", l: 1, c: "Argent" },
  { en: "to split the bill", fr: "partager l'addition", ex: "Let's split the bill.", l: 2, c: "Argent" },
  { en: "affordable", fr: "abordable", ex: "This hotel is affordable.", l: 2, c: "Argent" },
  { en: "a bargain", fr: "une bonne affaire", ex: "These shoes were a bargain.", l: 2, c: "Argent" },
  { en: "to afford", fr: "avoir les moyens de", ex: "We can afford a weekend away.", l: 2, c: "Argent" },
  { en: "the weather forecast", fr: "les prévisions météo", ex: "The forecast says rain.", l: 2, c: "Quotidien" },
  { en: "chilly", fr: "frisquet", ex: "It's a bit chilly tonight.", l: 2, c: "Quotidien" },
  { en: "to pour (with rain)", fr: "pleuvoir à verse", ex: "It's pouring outside.", l: 2, c: "Quotidien" },
  { en: "cozy", fr: "douillet, chaleureux", ex: "Your flat is so cozy.", l: 1, c: "Maison" },
  { en: "to tidy up", fr: "ranger", ex: "I need to tidy up before you come.", l: 1, c: "Maison" },
  { en: "the laundry", fr: "la lessive", ex: "I'm doing the laundry.", l: 1, c: "Maison" },
  { en: "to move in together", fr: "emménager ensemble", ex: "One day we'll move in together.", l: 2, c: "Maison" },
  { en: "a landlord", fr: "un propriétaire (bailleur)", ex: "My landlord is nice.", l: 2, c: "Maison" },
  { en: "the rent", fr: "le loyer", ex: "The rent is due on the 1st.", l: 1, c: "Maison" },
  { en: "to work out", fr: "faire du sport", ex: "I work out three times a week.", l: 1, c: "Santé" },
  { en: "to be sore", fr: "avoir des courbatures", ex: "I'm sore from yesterday's run.", l: 2, c: "Santé" },
  { en: "to catch a cold", fr: "attraper un rhume", ex: "I caught a cold.", l: 1, c: "Santé" },
  { en: "to get some rest", fr: "se reposer", ex: "Get some rest tonight.", l: 1, c: "Santé" },
  { en: "a nap", fr: "une sieste", ex: "I took a nap after lunch.", l: 1, c: "Santé" },
  { en: "to be in shape", fr: "être en forme", ex: "You're in great shape.", l: 1, c: "Santé" },
  { en: "to binge-watch", fr: "enchaîner les épisodes", ex: "We binge-watched the whole season.", l: 2, c: "Loisirs" },
  { en: "a spoiler", fr: "un spoiler, divulgâchage", ex: "No spoilers, please!", l: 1, c: "Loisirs" },
  { en: "a plot twist", fr: "un retournement de situation", ex: "That plot twist was crazy.", l: 2, c: "Loisirs" },
  { en: "to chill", fr: "se détendre", ex: "Let's just chill tonight.", l: 1, c: "Loisirs" },
  { en: "a board game", fr: "un jeu de société", ex: "We love board games.", l: 1, c: "Loisirs" },
  { en: "to be into", fr: "être fan de, aimer", ex: "I'm really into podcasts lately.", l: 2, c: "Loisirs" },
  { en: "actually", fr: "en fait (PAS « actuellement »)", ex: "Actually, I prefer tea.", l: 1, c: "Faux amis" },
  { en: "eventually", fr: "finalement, un jour (PAS « éventuellement »)", ex: "We'll eventually live together.", l: 2, c: "Faux amis" },
  { en: "a library", fr: "une bibliothèque (PAS « librairie »)", ex: "I study at the library.", l: 1, c: "Faux amis" },
  { en: "sensible", fr: "raisonnable (PAS « sensible »)", ex: "That's a sensible choice.", l: 2, c: "Faux amis" },
  { en: "to attend", fr: "assister à (PAS « attendre »)", ex: "I'll attend the wedding.", l: 2, c: "Faux amis" },
  { en: "to resume", fr: "reprendre (PAS « résumer »)", ex: "We'll resume after lunch.", l: 3, c: "Faux amis" },
  { en: "a deception", fr: "une tromperie (PAS « déception »)", ex: "It was a deception.", l: 3, c: "Faux amis" },
  { en: "to be disappointed", fr: "être déçu", ex: "I was disappointed by the ending.", l: 1, c: "Émotions" },
  { en: "grateful", fr: "reconnaissant", ex: "I'm grateful for you.", l: 2, c: "Émotions" },
  { en: "awkward", fr: "gênant, maladroit", ex: "That was an awkward moment.", l: 2, c: "Émotions" },
  { en: "to be thrilled", fr: "être ravi", ex: "I'm thrilled about the trip.", l: 2, c: "Émotions" },
  { en: "a hunch", fr: "une intuition", ex: "I have a hunch it will work.", l: 3, c: "Émotions" },
  { en: "to be homesick", fr: "avoir le mal du pays", ex: "She's homesick.", l: 2, c: "Émotions" },
  { en: "to be jealous", fr: "être jaloux", ex: "I'm a bit jealous of your weather.", l: 1, c: "Émotions" },
  { en: "to whisper", fr: "chuchoter", ex: "She whispered something.", l: 2, c: "Quotidien" },
  { en: "to yawn", fr: "bâiller", ex: "Stop yawning, it's contagious.", l: 2, c: "Quotidien" },
  { en: "to stare", fr: "fixer du regard", ex: "Why are you staring at me?", l: 2, c: "Quotidien" },
  { en: "to sigh", fr: "soupirer", ex: "He sighed and smiled.", l: 3, c: "Quotidien" },
  { en: "to giggle", fr: "glousser, rire bêtement", ex: "She giggled at my joke.", l: 3, c: "Quotidien" },
  { en: "to tease", fr: "taquiner", ex: "Stop teasing me!", l: 2, c: "Relations" },
  { en: "to flirt", fr: "flirter", ex: "Were you flirting with me?", l: 1, c: "Relations" },
  { en: "a date", fr: "un rencard", ex: "Our first date was in a café.", l: 1, c: "Relations" },
  { en: "to propose", fr: "demander en mariage", ex: "He proposed on the beach.", l: 2, c: "Relations" },
  { en: "to get engaged", fr: "se fiancer", ex: "They got engaged in June.", l: 2, c: "Relations" },
  { en: "in-laws", fr: "la belle-famille", ex: "We visit my in-laws on Sunday.", l: 2, c: "Relations" },
  { en: "a toddler", fr: "un bambin", ex: "The toddler was adorable.", l: 3, c: "Relations" },
  { en: "to raise (a child)", fr: "élever (un enfant)", ex: "Raising kids is hard.", l: 2, c: "Relations" },
  { en: "a nightmare", fr: "un cauchemar", ex: "I had a nightmare last night.", l: 1, c: "Quotidien" },
  { en: "to oversleep", fr: "ne pas se réveiller à temps", ex: "I overslept and missed the bus.", l: 2, c: "Quotidien" },
  { en: "to be running late", fr: "être en retard (en route)", ex: "I'm running late, sorry!", l: 2, c: "Quotidien" },
  { en: "to hurry up", fr: "se dépêcher", ex: "Hurry up, we'll be late!", l: 1, c: "Quotidien" },
  { en: "to be in a hurry", fr: "être pressé", ex: "I'm in a hurry this morning.", l: 1, c: "Quotidien" },
  { en: "to take your time", fr: "prendre son temps", ex: "Take your time, no rush.", l: 1, c: "Quotidien" },
  { en: "a habit", fr: "une habitude", ex: "It's a bad habit.", l: 1, c: "Quotidien" },
  { en: "to be used to", fr: "être habitué à", ex: "I'm used to the distance now.", l: 2, c: "Quotidien" },
  { en: "to get used to", fr: "s'habituer à", ex: "You'll get used to it.", l: 2, c: "Quotidien" },
  { en: "to cope with", fr: "faire face à, gérer", ex: "How do you cope with stress?", l: 3, c: "Émotions" },
  { en: "to struggle", fr: "avoir du mal, lutter", ex: "I'm struggling with this.", l: 2, c: "Émotions" },
  { en: "to thrive", fr: "s'épanouir", ex: "She thrives in her new job.", l: 3, c: "Émotions" },
  { en: "to settle down", fr: "se poser, s'installer", ex: "We want to settle down somewhere quiet.", l: 3, c: "Relations" },
  { en: "a goal", fr: "un objectif", ex: "What's your goal this year?", l: 1, c: "Boulot" },
  { en: "to achieve", fr: "accomplir, atteindre", ex: "You achieved so much.", l: 2, c: "Boulot" },
  { en: "a skill", fr: "une compétence", ex: "Cooking is a useful skill.", l: 1, c: "Boulot" },
  { en: "to be fluent", fr: "parler couramment", ex: "One day we'll be fluent.", l: 2, c: "Boulot" },
  { en: "to improve", fr: "s'améliorer", ex: "Your English is improving.", l: 1, c: "Boulot" },
  { en: "a challenge", fr: "un défi", ex: "Distance is a challenge.", l: 1, c: "Quotidien" },
  { en: "to be worth it", fr: "en valoir la peine", ex: "You're worth it.", l: 2, c: "Expressions" },
  { en: "to make it", fr: "y arriver, réussir", ex: "We'll make it.", l: 1, c: "Expressions" },
  { en: "so far", fr: "jusqu'ici", ex: "So far, so good.", l: 1, c: "Expressions" },
  { en: "by the way", fr: "au fait", ex: "By the way, I bought the tickets.", l: 1, c: "Expressions" },
  { en: "as soon as possible", fr: "dès que possible", ex: "Call me as soon as possible.", l: 1, c: "Expressions" },
  { en: "to be on my way", fr: "être en route", ex: "I'm on my way!", l: 1, c: "Expressions" },
  { en: "can't wait", fr: "avoir trop hâte", ex: "I can't wait to see you.", l: 1, c: "Amour" },
  { en: "to hold hands", fr: "se tenir la main", ex: "We walked holding hands.", l: 1, c: "Amour" },
  { en: "a kiss on the forehead", fr: "un baiser sur le front", ex: "He gave her a kiss on the forehead.", l: 2, c: "Amour" },
  { en: "to snuggle", fr: "se blottir", ex: "Let's snuggle and watch a movie.", l: 3, c: "Amour" },
  { en: "to spoil someone", fr: "gâter quelqu'un", ex: "I want to spoil you this weekend.", l: 2, c: "Amour" },
  { en: "a soulmate", fr: "une âme sœur", ex: "You're my soulmate.", l: 2, c: "Amour" },
  { en: "to cherish", fr: "chérir", ex: "I cherish every moment with you.", l: 3, c: "Amour" },
  { en: "to reassure", fr: "rassurer", ex: "Your message reassured me.", l: 2, c: "Relations" },
  { en: "to trust", fr: "faire confiance", ex: "I trust you completely.", l: 1, c: "Relations" },
  { en: "to apologize", fr: "s'excuser", ex: "I apologize for yesterday.", l: 1, c: "Relations" },
  { en: "to forgive", fr: "pardonner", ex: "Thank you for forgiving me.", l: 1, c: "Relations" },
  { en: "to compromise", fr: "trouver un compromis", ex: "Couples have to compromise.", l: 3, c: "Relations" },
  { en: "to argue", fr: "se disputer", ex: "We rarely argue.", l: 1, c: "Relations" },
  { en: "a misunderstanding", fr: "un malentendu", ex: "It was just a misunderstanding.", l: 2, c: "Relations" },
  { en: "to sort out", fr: "régler, résoudre", ex: "Let's sort this out tonight.", l: 2, c: "Relations" },
];
const ENGLISH_CATS = ['Amour', 'Relations', 'Quotidien', 'Émotions', 'Expressions', 'Voyage', 'Boulot', 'Food', 'Maison', 'Santé', 'Loisirs', 'Argent', 'Faux amis'];

/* Citation philosophique du jour : texte, auteur, question pour échanger */
const QUOTES = [
  { q: "Ce n'est pas parce que les choses sont difficiles que nous n'osons pas, c'est parce que nous n'osons pas qu'elles sont difficiles.", a: "Sénèque", p: "Qu'est-ce que tu n'oses pas en ce moment ?" },
  { q: "Connais-toi toi-même.", a: "Socrate", p: "Qu'as-tu appris sur toi récemment ?" },
  { q: "Le bonheur n'est pas une destination, c'est une manière de voyager.", a: "attribué à Margaret Lee Runbeck", p: "Comment tu voyages, toi, en ce moment ?" },
  { q: "Il n'y a qu'un bonheur dans la vie, c'est d'aimer et d'être aimé.", a: "George Sand", p: "Qu'est-ce qui te fait te sentir aimé·e ?" },
  { q: "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.", a: "Antoine de Saint-Exupéry", p: "Quel invisible tu vois chez l'autre ?" },
  { q: "Aimer, ce n'est pas se regarder l'un l'autre, c'est regarder ensemble dans la même direction.", a: "Antoine de Saint-Exupéry", p: "Dans quelle direction vous regardez ensemble ?" },
  { q: "L'homme est condamné à être libre.", a: "Jean-Paul Sartre", p: "Où sens-tu ta liberté aujourd'hui ?" },
  { q: "Ce qui ne me tue pas me rend plus fort.", a: "Friedrich Nietzsche", p: "Qu'est-ce qui t'a rendu plus fort·e ?" },
  { q: "Deviens ce que tu es.", a: "Friedrich Nietzsche (d'après Pindare)", p: "Qui es-tu en train de devenir ?" },
  { q: "Il faut imaginer Sisyphe heureux.", a: "Albert Camus", p: "Quel rocher tu pousses avec le sourire ?" },
  { q: "Au milieu de l'hiver, j'ai découvert en moi un invincible été.", a: "Albert Camus", p: "C'est quoi ton invincible été ?" },
  { q: "La vie n'est pas d'attendre que l'orage passe, c'est d'apprendre à danser sous la pluie.", a: "attribué à Sénèque", p: "Sous quelle pluie tu danses en ce moment ?" },
  { q: "Hâte-toi de bien vivre et songe que chaque jour est à lui seul une vie.", a: "Sénèque", p: "Qu'est-ce qui rendrait ce jour une vie entière ?" },
  { q: "Ce n'est pas le vent qui décide de ta destination, c'est l'orientation que tu donnes à ta voile.", a: "proverbe attribué à Jim Rohn", p: "Quelle voile tu orientes cette semaine ?" },
  { q: "Le sage ne s'afflige pas de ce qu'il n'a pas, il se réjouit de ce qu'il a.", a: "Épictète", p: "De quoi tu te réjouis, là, maintenant ?" },
  { q: "Ce ne sont pas les choses qui troublent les hommes, mais les jugements qu'ils portent sur les choses.", a: "Épictète", p: "Quel jugement tu pourrais lâcher aujourd'hui ?" },
  { q: "La vie est courte, l'art est long.", a: "Hippocrate", p: "Quel art tu voudrais avoir le temps d'apprendre ?" },
  { q: "Nous sommes ce que nous faisons de manière répétée. L'excellence n'est donc pas un acte mais une habitude.", a: "Aristote (d'après Will Durant)", p: "Quelle habitude te définit ?" },
  { q: "L'amitié est une âme en deux corps.", a: "Aristote", p: "Qu'est-ce qui vous rend « une âme » à deux ?" },
  { q: "Le doute est le commencement de la sagesse.", a: "Aristote", p: "De quoi tu doutes en ce moment, et c'est bien ?" },
  { q: "Je pense, donc je suis.", a: "René Descartes", p: "Quand tu ne penses à rien, tu es quoi ?" },
  { q: "Le cœur a ses raisons que la raison ne connaît point.", a: "Blaise Pascal", p: "Quelle raison du cœur tu suis en ce moment ?" },
  { q: "Tout le malheur des hommes vient d'une seule chose, qui est de ne savoir pas demeurer en repos dans une chambre.", a: "Blaise Pascal", p: "Tu sais rester en repos, toi ?" },
  { q: "Il faut cultiver notre jardin.", a: "Voltaire", p: "C'est quoi ton jardin à cultiver ?" },
  { q: "J'ai décidé d'être heureux parce que c'est bon pour la santé.", a: "Voltaire", p: "Tu décides quoi, aujourd'hui ?" },
  { q: "L'homme naît libre, et partout il est dans les fers.", a: "Jean-Jacques Rousseau", p: "Quels fers tu aimerais retirer ?" },
  { q: "Agis de telle sorte que tu traites l'humanité toujours en même temps comme une fin, et jamais simplement comme un moyen.", a: "Emmanuel Kant", p: "Qui tu traites comme une fin, aujourd'hui ?" },
  { q: "Ose savoir.", a: "Emmanuel Kant (d'après Horace)", p: "Qu'est-ce que tu aimerais oser savoir ?" },
  { q: "Ne pas rire, ne pas pleurer, ne pas détester, mais comprendre.", a: "Baruch Spinoza", p: "Qu'est-ce que tu essaies de comprendre ?" },
  { q: "Le désir est l'essence même de l'homme.", a: "Baruch Spinoza", p: "Quel désir te fait avancer ?" },
  { q: "La liberté consiste à faire tout ce qui ne nuit pas à autrui.", a: "Déclaration des droits de l'homme, 1789", p: "Où est ta limite entre liberté et l'autre ?" },
  { q: "Là où il y a une volonté, il y a un chemin.", a: "proverbe", p: "Quel chemin tu cherches ?" },
  { q: "Un voyage de mille lieues commence toujours par un premier pas.", a: "Lao Tseu", p: "Quel premier pas tu peux faire aujourd'hui ?" },
  { q: "Celui qui sait se contenter sera toujours content.", a: "Lao Tseu", p: "De quoi tu te contentes volontiers ?" },
  { q: "Celui qui connaît les autres est savant, celui qui se connaît lui-même est sage.", a: "Lao Tseu", p: "Qu'est-ce que tu connais mieux : les autres ou toi ?" },
  { q: "Choisis un travail que tu aimes et tu n'auras pas à travailler un seul jour de ta vie.", a: "attribué à Confucius", p: "Qu'est-ce que tu ferais sans jamais avoir l'impression de travailler ?" },
  { q: "L'homme qui déplace une montagne commence par déplacer de petites pierres.", a: "attribué à Confucius", p: "Quelle petite pierre aujourd'hui ?" },
  { q: "Ne fais pas aux autres ce que tu ne voudrais pas qu'on te fasse.", a: "Confucius", p: "Qu'est-ce que tu ne voudrais surtout pas qu'on te fasse ?" },
  { q: "Tout ce qui existe est la graine de ce qui sera.", a: "Marc Aurèle", p: "Quelle graine tu plantes en ce moment ?" },
  { q: "Tu as pouvoir sur ton esprit, pas sur les événements. Réalise cela, et tu trouveras la force.", a: "Marc Aurèle", p: "Sur quoi tu peux vraiment agir aujourd'hui ?" },
  { q: "La meilleure vengeance est de ne pas ressembler à celui qui t'a fait du mal.", a: "Marc Aurèle", p: "À qui tu ne veux surtout pas ressembler ?" },
  { q: "Il est plus facile de résister au premier désir qu'à tous ceux qui le suivent.", a: "Benjamin Franklin", p: "Quel premier désir tu surveilles ?" },
  { q: "Le bonheur est parfois caché dans l'inconnu.", a: "Victor Hugo", p: "Quel inconnu t'attire ?" },
  { q: "Le suprême bonheur de la vie, c'est la conviction qu'on est aimé.", a: "Victor Hugo", p: "Qu'est-ce qui te donne cette conviction ?" },
  { q: "Rien n'est plus puissant qu'une idée dont l'heure est venue.", a: "Victor Hugo", p: "Quelle idée a son heure venue chez toi ?" },
  { q: "On ne se baigne jamais deux fois dans le même fleuve.", a: "Héraclite", p: "Qu'est-ce qui a changé en toi depuis un an ?" },
  { q: "Rien n'est permanent, sauf le changement.", a: "Héraclite", p: "Quel changement tu accueilles ?" },
  { q: "Ce qui est à toi, c'est ce que tu donnes.", a: "proverbe", p: "Qu'est-ce que tu as donné cette semaine ?" },
  { q: "Vivre, ce n'est pas attendre. C'est agir.", a: "proverbe", p: "Qu'est-ce que tu attends encore ?" },
  { q: "Le vrai voyage de découverte ne consiste pas à chercher de nouveaux paysages, mais à avoir de nouveaux yeux.", a: "Marcel Proust", p: "Qu'est-ce que tu regarderais avec de nouveaux yeux ?" },
  { q: "Soyons reconnaissants aux personnes qui nous donnent du bonheur : elles sont les charmants jardiniers par qui nos âmes sont fleuries.", a: "Marcel Proust", p: "Qui est ton jardinier ?" },
  { q: "L'enfer, c'est les autres.", a: "Jean-Paul Sartre", p: "Et le paradis, c'est qui ?" },
  { q: "On ne naît pas femme, on le devient.", a: "Simone de Beauvoir", p: "Qu'est-ce que tu es en train de devenir par choix ?" },
  { q: "Le présent est la seule chose qui n'ait pas de fin.", a: "Simone de Beauvoir", p: "Qu'est-ce que tu ressens là, tout de suite ?" },
  { q: "Être libre, ce n'est pas seulement se débarrasser de ses chaînes, c'est vivre d'une façon qui respecte et renforce la liberté des autres.", a: "Nelson Mandela", p: "Comment tu renforces la liberté de l'autre ?" },
  { q: "Je ne perds jamais. Soit je gagne, soit j'apprends.", a: "attribué à Nelson Mandela", p: "Qu'as-tu appris d'un échec récent ?" },
  { q: "La folie, c'est de faire toujours la même chose et de s'attendre à un résultat différent.", a: "attribué à Albert Einstein", p: "Qu'est-ce que tu répètes en attendant autre chose ?" },
  { q: "L'imagination est plus importante que le savoir.", a: "Albert Einstein", p: "Qu'est-ce que tu imagines pour vous deux ?" },
  { q: "La vie, c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre.", a: "Albert Einstein", p: "Tu avances vers quoi, cette semaine ?" },
  { q: "Sois le changement que tu veux voir dans le monde.", a: "attribué à Gandhi", p: "Quel changement tu incarnes ?" },
  { q: "Le bonheur, c'est lorsque vos actes sont en accord avec vos paroles.", a: "attribué à Gandhi", p: "Où tes actes et tes mots sont-ils alignés ?" },
  { q: "Là où il y a de l'amour, il y a de la vie.", a: "Gandhi", p: "Où est la vie, chez toi, en ce moment ?" },
  { q: "Un ami, c'est quelqu'un qui vous connaît bien et qui vous aime quand même.", a: "proverbe", p: "Qu'est-ce que l'autre connaît de toi et aime quand même ?" },
  { q: "Ne juge pas chaque jour à la récolte que tu fais mais aux graines que tu sèmes.", a: "Robert Louis Stevenson", p: "Quelle graine tu as semée aujourd'hui ?" },
  { q: "La patience est amère, mais son fruit est doux.", a: "Jean-Jacques Rousseau", p: "Quel fruit tu attends patiemment ?" },
  { q: "La seule chose que nous ayons à craindre est la crainte elle-même.", a: "Franklin D. Roosevelt", p: "Quelle crainte tu pourrais regarder en face ?" },
  { q: "Vivez comme si vous deviez mourir demain. Apprenez comme si vous deviez vivre toujours.", a: "attribué à Gandhi", p: "Qu'est-ce que tu apprendrais si tu avais tout le temps ?" },
  { q: "Ce que l'on conçoit bien s'énonce clairement.", a: "Nicolas Boileau", p: "Qu'est-ce que tu aimerais dire plus clairement ?" },
  { q: "Le plus grand risque est de ne prendre aucun risque.", a: "attribué à Mark Zuckerberg", p: "Quel risque tu évites ?" },
  { q: "Ce qui compte ne peut pas toujours être compté, et ce qui peut être compté ne compte pas forcément.", a: "William Bruce Cameron", p: "Qu'est-ce qui compte et qu'on ne compte pas ?" },
  { q: "Le temps que tu perds pour ta rose fait ta rose si importante.", a: "Antoine de Saint-Exupéry", p: "Pour qui tu « perds » du temps avec joie ?" },
  { q: "Tu deviens responsable pour toujours de ce que tu as apprivoisé.", a: "Antoine de Saint-Exupéry", p: "De quoi tu te sens responsable ?" },
  { q: "Le silence est un ami qui ne trahit jamais.", a: "Confucius", p: "Quand le silence te fait du bien ?" },
  { q: "La simplicité est la sophistication suprême.", a: "attribué à Léonard de Vinci", p: "Qu'est-ce que tu pourrais simplifier ?" },
  { q: "Qui veut faire quelque chose trouve un moyen, qui ne veut rien faire trouve une excuse.", a: "proverbe arabe", p: "Quelle excuse tu te racontes ?" },
  { q: "Tomber sept fois, se relever huit.", a: "proverbe japonais", p: "De quelle chute tu t'es relevé·e ?" },
  { q: "Le moment présent a un avantage sur tous les autres : il nous appartient.", a: "Charles Caleb Colton", p: "Qu'est-ce que tu fais de ce moment-là ?" },
  { q: "Un homme qui ne lit pas ne vit qu'une vie. Le lecteur en vit mille.", a: "George R. R. Martin", p: "Quelle vie tu as vécue dans un livre ?" },
  { q: "L'amour est la seule chose qui grandit quand on la partage.", a: "proverbe", p: "Comment tu partages, toi ?" },
  { q: "Le plus grand voyageur n'est pas celui qui a fait dix fois le tour du monde, mais celui qui a fait une seule fois le tour de lui-même.", a: "attribué à Gandhi", p: "Où en es-tu du tour de toi-même ?" },
  { q: "Ce que tu penses, tu le deviens.", a: "attribué à Bouddha", p: "À quoi tu penses le plus souvent ?" },
  { q: "Trois choses ne peuvent être cachées longtemps : le soleil, la lune et la vérité.", a: "attribué à Bouddha", p: "Quelle vérité tu as envie de dire ?" },
  { q: "La douleur est inévitable, la souffrance est facultative.", a: "proverbe bouddhiste", p: "Quelle souffrance tu pourrais poser ?" },
  { q: "Chaque matin, nous naissons de nouveau. Ce que nous faisons aujourd'hui est ce qui compte le plus.", a: "attribué à Bouddha", p: "Tu renais comment ce matin ?" },
  { q: "Il vaut mieux allumer une bougie que maudire l'obscurité.", a: "proverbe chinois", p: "Quelle bougie tu peux allumer ?" },
  { q: "Un cœur qui aime est toujours jeune.", a: "proverbe grec", p: "Qu'est-ce qui te garde jeune ?" },
  { q: "Le bonheur est la seule chose qui se double si on le partage.", a: "Albert Schweitzer", p: "Quel bonheur tu as doublé récemment ?" },
  { q: "L'important n'est pas ce qu'on fait de nous, mais ce que nous faisons nous-mêmes de ce qu'on a fait de nous.", a: "Jean-Paul Sartre", p: "Qu'est-ce que tu fais de ton histoire ?" },
  { q: "Savoir écouter, c'est posséder, outre le sien, le cerveau des autres.", a: "Léonard de Vinci", p: "Qui tu pourrais mieux écouter ?" },
  { q: "Ce qui embellit le désert, c'est qu'il cache un puits quelque part.", a: "Antoine de Saint-Exupéry", p: "C'est quoi ton puits caché ?" },
];
